
# source directory -- will be provided by the js sources generation script
source_dir: $PYLATEXENC_SRC_DIR

# output directory -- will create a pylatexenc/ subfolder
target_dir: $PREPROCESS_LIB_OUTPUT_DIR

# which modules to preprocess
module_list:
  - 'pylatexenc.latexnodes'
  - 'pylatexenc.macrospec'
  - 'pylatexenc.latexwalker'
  - 'pylatexenc.latexencode'

# features
enabled_features:
  keep_future_statements: False
  keep_relative_imports: False
  keep_super_arguments: False
  keep_dict_with_generator: False
  keep_frozenset: False
  keep_logger_debug: True
  guards:
    PYTHON2_SUPPORT_CODE: False
    PYLATEXENC1_LEGACY_SUPPORT_CODE: False
    PYLATEXENC2_LEGACY_SUPPORT_CODE: False
    PYLATEXENC_GET_DEFAULT_SPECS_FN: False
    LATEXWALKER_HELPERS: False
    DEBUG_SET_EQ_ATTRIBUTE: False
  patches:
    UNIQUE_OBJECT_ID: |
      import unique_object_id
      fn_unique_object_id = unique_object_id.fn_unique_object_id

    # Always specify u2lobj= to callables (JS will silently ignore extra args)
    LATEXENCODE_CALLABLE_ACCEPTS_U2LOBJ_ARG: |
      def _callable_accepts_u2lobj_arg(fn):
          return True
